name: "Install Apprentice Licenses"
description: "Install Houdini Apprentice licenses for the duration of the tests."
branding:
  icon: "arrow-up-right"
  color: "orange"
inputs:
  client_id:
    description: "The SideFX Web API client_id value to use."
    required: true

  client_secret_key:
    description: "The SideFX Web API client_secret_key value to use."
    required: true

runs:
  using: "composite"

  steps:
    - if: inputs.client_id == ''
      run: echo client_id is empty && exit 1
      shell: bash

    - if: inputs.client_secret_key == ''
      run: echo client_secret_key is empty && exit 1
      shell: bash

    - run: python3 -m pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash

    - run: sesinetd
      shell: bash

    - run: python3 ${GITHUB_ACTION_PATH}/install_apprentice_keys.py ${{ inputs.client_id }} ${{ inputs.client_secret_key }}
      shell: bash

    - run: hserver -h localhost:1715
      shell: bash
