# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        houdini-version:
          - "19.5"  # Python 3.9
          - "20.0"  # Python 3.10

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Unit Tests

      - name: Install unit test dependencies
        run: python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      # Integration tests

      - name: Install Apprentice Licenses
        uses: ./

        with:
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}

      - name: Test hserver is running
        run: hserver -l
        shell: bash
